### ISSUE TITLE
Clonetech primers

### ISSUE THREAD

**Issue by fmarletaz** [PacificBiosciences/barcoding#10]
Hi - 

I am trying `lima` as part of the isoseq pipeline on sequel data. I used the clontech primers suggested on the isoseq page: 
```
>primer_5p
AAGCAGTGGTATCAACGCAGAGTACATGGG
>primer_3p
GTACTCTGCGTTGATACCACTGCTT
```
My problem is that most of my reads are discarded as show a 3p-3p orientation (see below). The command I am using is `lima ccs.bam primers.fa dmx.ccs.bam --isoseq --no-pbi -j 8`. Am I doing something wrong? I also noticed that the reverse complement of the 3' primer is in the 5' primer, is that normal? 

Example of output: 
```
ZMWs input                (A) : 547991
ZMWs above all thresholds (B) : 1727 (0%)
ZMWs below any threshold  (C) : 546264 (100%)

ZMW marginals for (C):
Below min length              : 405 (0%)
Below min score               : 0 (0%)
Below min end score           : 42692 (8%)
Below min passes              : 77829 (14%)
Below min score lead          : 0 (0%)
Below min ref span            : 34961 (6%)
Without adapter               : 100 (0%)
Undesired 5p--5p pairs        : 3736 (1%)
Undesired 3p--3p pairs        : 456228 (84%)
Undesired no hit              : 100 (0%)

ZMWs for (B):
With different barcodes       : 1727 (100%)
Coefficient of correlation    : 0%

ZMWs for (A):
Allow diff barcode pair       : 470162 (86%)
Allow same barcode pair       : 470162 (86%)

Reads for (B):
Above length                  : 1727 (100%)
Below length                  : 0 (0%)
```

**Comment by Magdoll** [comment]
Hi @fmarletaz ,

Can you please confirm your Iso-Seq library is made using the standard recommendation - the Clontech SMARter cDNA kit. And no barcodes were used? (the library is not multiplexed)

If so, then yes -- that is the correct set of Clontech primers. The Clontech primers are mostly symmetric except the 5' end has an additional overhang of ATGGG. 

The fact that you see mostly 3p--3p pairs, suggest a chance that your library has a high number of artifacts. It's possible the TSO overhang (ATGGG) is missing on the supposed 5' end. Or maybe there's a lot of PCR chimeras with polyAs on both ends. It's little hard to tell what is wrong - the only certain here is something is probably wrong - but we can take a look at the CCS data to find out.

I suggest converting the CCS data to fasta format (if you haven't already done so). If the input is ccs.bam, then you can convert it using

```
bamtools convert -format fasta -in ccs.bam > ccs.fasta
```

Using the Clontech primer pairs above, take a look at what the sequences look like? Can you find the 5' primer with the ATGGG overhang? The structure should be:

5' (AAGCAGTGGTATCAACGCAGAGTACATGGG) -- insert -- (A)n -- GTACTCTGCGTTGATACCACTGCTT

or the reverse complement of the above, since CCS can be generated in either direction.
