### ISSUE TITLE
advice for parameters

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/barcoding#6]
Hi
I ran lima with standard settings on the [8-plex-Ecoli-Multiplexed-Microbial-Assembly](https://github.com/PacificBiosciences/DevNet/wiki/8-plex-Ecoli-Multiplexed-Microbial-Assembly) data and found only a very low number of classified reads for each sample.

`$ lima -s --split-bam Ecoli_8plex_demo.barcoded.subreads.bam barcodes_8plex.fasta Ecoli_8plex_split.bam`

the result summary indicates two main causes for exclusion

```
$ cat Ecoli_8plex_split.lima.summary
ZMWs input                (A) : 494807
ZMWs above all thresholds (B) : 36305 (7%)
ZMWs below any threshold  (C) : 458502 (93%)

ZMW marginals for (C):
Below min length              : 2 (0%)
Below min score               : 0 (0%)
Below min end score           : 0 (0%)
Below min passes              : 0 (0%)
Below min score lead          : 262672 (57%)
Below min ref span            : 116769 (25%)
Without adapter               : 189732 (41%)
Undesired diff barcode pairs  : 1375 (0%)

ZMWs for (B):
With same barcode             : 36305 (100%)
Coefficient of correlation    : 22.7%

ZMWs for (A):
Allow diff barcode pair       : 156210 (32%)
Allow same barcode pair       : 305075 (62%)

Reads for (B):
Above length                  : 97892 (100%)
Below length                  : 359 (0%)

$ cat Ecoli_8plex_split.lima.counts
IdxFirst        IdxCombined     IdxFirstNamed   IdxCombinedNamed        Counts  MeanScore
0       0       lbc1    lbc1    5220    36
1       1       lbc29   lbc29   3359    42
2       2       lbc34   lbc34   3973    43
3       3       lbc38   lbc38   3987    39
4       4       lbc40   lbc40   5427    40
5       5       lbc48   lbc48   2947    47
6       6       lbc52   lbc52   5770    41
7       7       lbc70   lbc70   5622    37
```

Which parameter and values would you advise to add to the lima command to rescue more subreads in order to assemble each bacterium separately? (now very poor with the 8 extracted subsets)

```
  -y,--min-score-lead            The minimal score lead required to call a barcode pair significant. [10]
  -r,--min-ref-span              Minimum reference span relative to the barcode length. [0.5]
```

can we do something about the 'Without adapter  : 189732 (41%)' ?

Thanks in advance

**Comment by jrharting** [comment]
Hi,

That particular dataset was posted a couple years ago and was barcoded prior to upload, albeit by our previous barcoding tool `bam2bam`.  This means that all barcode sequences were trimmed from the subreads BAM and barcoding tags `bcf/bcr` (indices) and `bq` (barcode score) are assigned to each subread.  

Running Lima should give you this kind of result because its scoring random sequence at the ends of the insert.  You can assemble these data directly by using `dataset split --barcodes` and then importing the split datasets into SMRT-Link or run jobs on the command line.

Incidentally, this particular example was all the same strain of _E. coli_ and can therefore be assembled from the whole subreadset by ignoring the barcodes altogether.  Or from any random subset of reads if you desire.

Finally, the 41% of reads with no adapter is the unfortunate result of a trade-off in multiplexed assembly between wanting a library long enough to bridge large repeats and generate a good assembly, but not so long that the polymerase in the sequencer never reaches the other end of the insert, where the barcodes are.  If the inserts are all really short, most get barcodes, but are not as useful for assembly.  If the reads are too long, you cannot bin them by sample because you never sequence a barcode!

Best,
John

**Comment by splaisan** [comment]
Thanks a lot John,
This explains it all.
I have now assembled from the whole merge and am producing CCS reads to correct the circlator output and to polish the final assembly as listed in the wiki and circlator pages.
I hope this will lead to a good practice of HGAP4 CCS, circlator, and also motif analysis
Best,
Stephane
