### ISSUE TITLE
Some  questions about lima demultiplex software

### ISSUE THREAD

**Issue by wlhCNU** [PacificBiosciences/barcoding#8]
When I demultiplex IsoSeq data, the lima.summary results was same,  no matter how the  --min-end-score (0 or 50) parameters are set.  Is this normal ?
  To add a further problem,  my sample single end  barcodes were connected to  3` primer sequences.  Only the 3' 5' primer sequences were offered with barcode sequences, can we demultiplex IsoSeq data successfully. Otherwise we will fail to demultiplex IsoSeq data with only barcode sequences were in barcode file. Were  3' 5' primer sequences essential factor to demultiplex IsoSeq data successfully ?   Either 3'  primer sequences or  5' primer sequences were missing in target subreads sequences  will led to failure to  demultiplex these subreads sequences, is this the normal  phenomenon ?  
    When  the dumultiplex data was used  to alignment the corresponding genome sequences, we find that very few sequences doesnot match the corresponding genome sequences, but matched other sample's genome sequences.  Is it  possible that these special sequnces were dumultiplexed to incorrect samples?

**Comment by armintoepfer** [comment]
>When I demultiplex IsoSeq data, the lima.summary results was same, no matter how the --min-end-score (0 or 50) parameters are set. Is this normal ?

As stated in the docs, `--isoseq` mode overrides many parameters. You can't change them. That's a feature not a bug. It guarantees you the optimal result, balancing sensitivity and false discovery rate.

>Were 3' 5' primer sequences essential factor to demultiplex IsoSeq data successfully ? 

https://github.com/PacificBiosciences/barcoding#how-can-i-demultiplex-isoseq-data
You need to provide the 5' primer and the barcoded 3' primer, like in the example.

>Is it possible that these special sequnces were dumultiplexed to incorrect samples?

Internal benchmarks show ~1% false discovery rate. This can be due to 
- wrongly assigning sequences to the wrong barcodes in the demuxing
- badly synthesized barcoded primers, for example, the molecule is only 75% of length
- impurity of your ordered barcoded primers
- impurity during your library prep.

As you can see, at each step something can go wrong and likely, what you see is cumulative of a little bit everywhere.
