### ISSUE TITLE
lima input file format and probe-based linear barcoded adapters demultiplexing

### ISSUE THREAD

**Issue by imneuro** [PacificBiosciences/barcoding#9]
Hi there, 

I get preliminary processed subread.bam file from SEQUEL sequencing. It was processed in SMRT LINK 5.1.0, which only has lima1.0.0. The library designed are probe-based linear barcoded adapters. And I was told to do CCS read demultiplexing. However, the instruction is not clear. Could you instructed on how to use lima and ccs to demultiplexing this case? Shall I switch to lima 1.6.2 rather than lima 1.0.0? 

In addition, besides the bam as lima input, any other format were supported? I have tried fasta format, and lima 1.0.0 doesn't support it.

Best,
Xin

**Comment by armintoepfer** [comment]
Hi Xin,

please contact PacBio techsupport or your local representative. They will help you out.

Best,
Armin

**Comment by armintoepfer** [comment]
Let me shed some light on it.

>The library designed are probe-based linear barcoded adapters. 
https://github.com/PacificBiosciences/barcoding#what-is-a-universal-spacer-sequence-and-how-does-it-affect-demultiplexing

>However, the instruction is not clear. Could you instructed on how to use lima and ccs to demultiplexing this case? 
Instructions how to use it on CCS are described here:
https://github.com/pacificbiosciences/barcoding#execution

>Shall I switch to lima 1.6.2 rather than lima 1.0.0?
For probe-based linear barcoded adapters, yes.

>In addition, besides the bam as lima input, any other format were supported? 
No and nothing is planned. PacBio data is in unaligned BAM format.

 - Armin

**Comment by imneuro** [comment]
These inputs are more helpful. 

In order to generate ccs.bam file from subread.bam file (new format with subread.bam.pbi) ,  shall I use ccs 3.0.0 in SMRT link 5.1.0 package or pbcss in https://github.com/PacificBiosciences/unanimity .

In addition, I need to create dockerfile to use these tools. May I install SMRT Link 5.1.0,  unanimity, and lima 1.6.2 in one image?  Any suggestion on installation order and user permission? I am aware of the computation and storage requirements for SMRT LINK software, yet AWS cloud is the only environment I have. I wonder if AWS instance with 32cpus and 244GB with 2TB EBS volume work well (no local disk) is enough for probe-based linear barcoded adapters demultiplexing.

**Comment by armintoepfer** [comment]
You can run lima on CCS data on your laptop. Sure, more cores, the better, but memory usage should stay flat as it's streaming and we are mostly limited by IO. CCS, as you might know, needs a LOT of CPU power!

Regarding which CCS version, do you want the officially vetted ISO compliant version that comes with SMRT Link or a pre-release version from bioconda? That's the difference. Bioconda version is newer and not ISO compliant.

At least I can't help you out with docker, since I'm not a cloud user. If I were you and I don't need ISO compliance, I'd only install pbccs and lima packages from bioconda and go with it.
